worker_processes auto;
error_log logs/error.log warn;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/json;

    log_format main '$remote_addr [$time_local] "$request" $status $request_time';
    access_log logs/access.log main;

    sendfile on;
    keepalive_timeout 120;

    # 共享内存字典
    lua_shared_dict queue_store 20m;
    lua_shared_dict queue_limiter 10m;

    lua_package_path "/usr/local/openresty/lualib/?.lua;;";
    lua_load_resty_core on;

    include /etc/nginx/conf.d/*.conf;
}
