modules:
  http_2xx:
    prober: http
    timeout: 10s
    http:
      preferred_ip_protocol: ip4
      valid_status_codes: [200, 401, 403, 405, 429]
      method: GET
      fail_if_ssl: false
      fail_if_not_ssl: true

  tcp_connect:
    prober: tcp
    timeout: 5s
